name: CI
on:
  pull_request:
    branches: [dev]
jobs:
     test-build:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v2
         - name: Install node modules
           uses: actions/setup-node@v1
           with:
             node-version: "12.x"
         - run: npm install
         - name: Check code formatting
           run: npm run format:check
         - name: Format code
           if: failure()
           run: npm run format
         - name: Push formated code
           run: |
             git status
             git add -A
             git commit -m "Formating code"
             git push
         - name: Rerun Check code formatting
           run: npm run format:check
         - name: Trigger MWS jenkins test build  
           run: echo "Run Jenkins Test Build"
           env:
             CI: true