name: CI
on:
  pull_request:
    branches: [dev]
jobs:
     test-build:
       runs-on: ubuntu-latest
       steps:
         - uses: actions/checkout@v2
         - name: Code checks
           uses: actions/setup-node@v1
           with:
             node-version: "12.x"
         - run: npm ci 
         - run: npm run format:check
         - run: echo "Run Jenkins Test Build"
           env:
             CI: true