name: CI
on:
  pull_request:
    branches: [dev]
jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use node JS
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm install
      - run: npm i -dev jest-circus
      - run: npm run format:check
      - run: npm test -- --coverage
        env:
          CI: true
